name: Run Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Stockfish 20250213
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar  # Cài đặt tar nếu chưa có
        wget https://github.com/official-stockfish/Stockfish/releases/download/stockfish-dev-20250213-fa6c30af/stockfish-ubuntu-x86-64-bmi2.tar  # URL mới cho Stockfish
        
        # Liệt kê nội dung trong tệp nén để kiểm tra tên tệp stockfish
        tar -tvf stockfish-ubuntu-x86-64-bmi2.tar
        
        # Giải nén tệp Stockfish
        tar -xvf stockfish-ubuntu-x86-64-bmi2.tar 
        
        # In ra danh sách các tệp đã giải nén
        ls -l  
        
        # Tìm tất cả các tệp liên quan đến stockfish trong thư mục hiện tại
        find . -name "stockfish*"  

        # Tạo thư mục engines nếu chưa có
        mkdir -p ./engines
        
        # Kiểm tra tên tệp Stockfish và di chuyển nó vào thư mục engines
        sudo mv stockfish-ubuntu-x86-64-bmi2 ./engines/stockfish-ubuntu-x86-64-bmi2

    - name: Run the bot
      env:
        LICHESS_API_KEY: ${{ secrets.LICHESS_API_KEY }}  # Thêm API Key của bạn vào GitHub Secrets
      run: |
        python user_interface.py --matchmaking  # Chạy lệnh với đối số --matchmaking
